title: ACT Rules demo
email: wilco.fiers@deque.com
description: >
  Demo implementation of Accessibility Conformance Testing Rules Format 1.0
baseurl: "/wcag-act-rules"
url: "https://w3c.github.io"

# Build settings
markdown: kramdown

collections:
  rules:
    output: true
  rule-tests:
    output: true

defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      path: ""
      type: rules
    values:
      layout: rule
  - scope:
      path: ""
      type: rule-tests
    values:
      layout: testcase