title: ACT Rules demo
email: wilco.fiers@deque.com
description: >
  Demo implementation of Accessibility Conformance Testing Rules Format 1.0
baseurl: "/act-rules"
url: "https://wilcofiers.github.io"
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown

collections:
  rules:
    output: true

defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      path: ""
      type: rules
    values:
      layout: rule